classdef feedback
    %FEEDBACK feedback contains the data describing the 
    % "circumstances of transmission" and is generated by the user.
    % One feedback object descibes the transmission circumstances between
    % one basestation and one user entity.
    
    properties
        n_b_antennas; % number of base station antennas
        n_u_antennas; % number of user entity antennas
        n_subcarriers; %number of subcarriers
        CQI; % Channel quality indicator: (#subcar) X (min(#b_antennas,#u_antennas))
        RI; % Rank Indicator: (#subcar) X 1; tells number of possible streams
        PMI = 0; % Precoding Matrix indicator
        
        %replace with parameters for number of subcarriers/base
        %antennas/user antennas
        
    end
    
    methods
        function obj = feedback()
            parameters = feed_param();
            obj.n_b_antennas = parameters(2).n_b_antennas;
            obj.n_u_antennas = parameters(2).n_u_antennas;
            obj.n_subcarriers = parameters(2).n_subcarriers;
            
            % get max number of streams
            if obj.n_u_antennas < obj.n_b_antennas
                max = obj.n_u_antennas;
            else
                max = obj.n_b_antennas;
            end
            % initialize CQI
            obj.CQI = zeros(obj.n_subcarriers,max);
            obj.RI = zeros(obj.n_subcarriers,1);
            obj.PMI = 0;                    
        end    
        
        function obj = fill_randomly(self)
            obj = feedback();
            
            % get max number of streams
            if obj.n_u_antennas < obj.n_b_antennas
                max = obj.n_u_antennas;
            else
                max = obj.n_b_antennas;
            end
            
            %set values randomly
            obj.CQI = randi(15,obj.n_subcarriers,max);
            obj.RI= randi(max,obj.n_subcarriers,1);
            obj.PMI = randi(10);            
            
            
        end
        
    end
    
end

