classdef feedback
    %FEEDBACK feedback contains the data describing the 
    % "circumstances of transmission" and is generated by the user.
    % One feedback object descibes the transmission circumstances between
    % one basestation and one user entity.
    
    properties
        n_b_antennas=1; % number of base station antennas
        n_u_antennas=1; % number of user entity antennas
        CQI = zeros(25,1); % Channel quality indicator: (#subcar) X (min(#b_antennas,#u_antennas))
        RI = zeros(25,1); % Rank Indicator: (#subcar) X 1; tells number of possible streams
        PMI = 0; % Precoding Matrix indicator
        
    end
    
    methods
        function obj = feedback(n_b_antennas_attr, n_u_antennas_attr)
            obj.n_b_antennas = n_b_antennas_attr;
            obj.n_u_antennas = n_u_antennas_attr;
            
            % get max number of streams
            if n_u_antennas_attr < n_b_antennas_attr
                max = n_u_antennas_attr;
            else
                max = n_b_antennas_attr;
            end
            % initialize CQI
            obj.CQI = zeros(25,max);
            obj.RI = zeros(25,1);
            obj.PMI = 0;                    
        end    
        
        function obj = fillRandomly(self)
            obj = feedback(self.n_b_antennas,self.n_u_antennas);
            
            % get max number of streams
            if obj.n_u_antennas < obj.n_b_antennas_attr
                max = obj.n_u_antennas;
            else
                max = obj.n_b_antennas;
            end
            
            %set values randomly
            obj.CQI = randi(15,25,max);
            obj.RI= randi(max,25,1);
            obj.PMI = randi(10);            
            
            
        end
        
    end
    
end

